version: '3.3'
services:
  web:
    build: .
    ports:
    - 5000:5000
    volumes:
      - .:/app

  sqliteweb:
    image: tomdesinto/sqliteweb
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./db/database:/db/database
    command: database